"""Additional popular provider catalog entries."""

from __future__ import annotations

from .provider_catalog import ProviderDefinition


def extra_provider_definitions() -> tuple[ProviderDefinition, ...]:
    return (
        ProviderDefinition(
            provider_id="cohere",
            display_name="Cohere",
            transport_id="openai_chat_compatible",
            catalog_summary="Use Cohere models through Cohere's OpenAI-compatible Compatibility API.",
            onboarding_hint="Choose a Command model, attach a Cohere API key, and validate the Compatibility API route.",
            default_base_url="https://api.cohere.ai/compatibility/v1",
            default_model_id="command-a-03-2025",
            required_secret_keys=("api_key",),
            required_config_keys=("model_id",),
            capability_flags=("chat", "embeddings"),
            model_hints=("command-a-03-2025", "command-a-plus-05-2026", "command-r-plus-08-2024"),
            supports_custom_base_url=False,
            listing_priority=56,
            docs_url="https://docs.cohere.com/docs/compatibility-api",
            provider_kind="first_party",
            auth_method="api_key",
            auth_type="api_key",
            env_var_names=("COHERE_API_KEY",),
            base_url_env_var="COHERE_BASE_URL",
            metadata={"surface": "first_party", "unsupported_capabilities": "reasoning"},
        ),
        ProviderDefinition(
            provider_id="perplexity",
            display_name="Perplexity Agent API",
            transport_id="openai_responses",
            catalog_summary="Use Perplexity's OpenAI-compatible Agent API for grounded model routing.",
            onboarding_hint="Attach a Perplexity API key and use the Responses-compatible Agent API endpoint.",
            default_base_url="https://api.perplexity.ai/v1",
            default_model_id="openai/gpt-5-mini",
            required_secret_keys=("api_key",),
            required_config_keys=("model_id",),
            capability_flags=("chat",),
            model_hints=("openai/gpt-5.5", "openai/gpt-5-mini", "anthropic/claude-sonnet-4.6"),
            supports_custom_base_url=False,
            listing_priority=57,
            docs_url="https://docs.perplexity.ai/docs/agent-api/openai-compatibility",
            provider_kind="first_party",
            auth_method="api_key",
            auth_type="api_key",
            env_var_names=("PERPLEXITY_API_KEY",),
            base_url_env_var="PERPLEXITY_BASE_URL",
            metadata={"surface": "first_party", "unsupported_capabilities": "embeddings"},
        ),
        ProviderDefinition(
            provider_id="cerebras",
            display_name="Cerebras",
            transport_id="openai_chat_compatible",
            catalog_summary="Use Cerebras Inference through its OpenAI-compatible high-speed endpoint.",
            onboarding_hint="Attach a Cerebras API key and choose a production or preview Cerebras-served model.",
            default_base_url="https://api.cerebras.ai/v1",
            default_model_id="gpt-oss-120b",
            required_secret_keys=("api_key",),
            required_config_keys=("model_id",),
            capability_flags=("chat",),
            model_hints=("gpt-oss-120b", "zai-glm-4.7", "llama3.1-8b"),
            supports_custom_base_url=False,
            listing_priority=58,
            docs_url="https://inference-docs.cerebras.ai/resources/openai",
            provider_kind="first_party",
            auth_method="api_key",
            auth_type="api_key",
            env_var_names=("CEREBRAS_API_KEY",),
            base_url_env_var="CEREBRAS_BASE_URL",
            metadata={"surface": "first_party", "unsupported_capabilities": "embeddings"},
        ),
        ProviderDefinition(
            provider_id="nvidia",
            display_name="NVIDIA NIM",
            transport_id="openai_chat_compatible",
            catalog_summary="Use NVIDIA API Catalog / NIM hosted models through the OpenAI-compatible endpoint.",
            onboarding_hint="Attach an NVIDIA API key and choose a NIM-hosted model from the API catalog.",
            default_base_url="https://integrate.api.nvidia.com/v1",
            default_model_id="nvidia/llama-3.3-nemotron-super-49b-v1",
            required_secret_keys=("api_key",),
            required_config_keys=("model_id",),
            capability_flags=("chat",),
            model_hints=(
                "nvidia/llama-3.3-nemotron-super-49b-v1",
                "nvidia/nemotron-3-super-120b-a12b",
                "nvidia/llama-3.1-nemotron-nano-vl-8b-v1",
            ),
            supports_custom_base_url=False,
            listing_priority=59,
            docs_url="https://docs.api.nvidia.com/nim/reference/llm-apis",
            provider_kind="first_party",
            auth_method="api_key",
            auth_type="api_key",
            env_var_names=("NVIDIA_API_KEY", "NVIDIA_NIM_API_KEY"),
            base_url_env_var="NVIDIA_BASE_URL",
            metadata={"surface": "first_party", "unsupported_capabilities": "embeddings"},
        ),
        ProviderDefinition(
            provider_id="siliconflow",
            display_name="SiliconFlow",
            transport_id="openai_chat_compatible",
            catalog_summary="Use SiliconFlow's OpenAI-compatible model cloud for Chinese and open-source model families.",
            onboarding_hint="Attach a SiliconFlow key and choose a Qwen, DeepSeek, Kimi, GLM, or other hosted model.",
            default_base_url="https://api.siliconflow.cn/v1",
            default_model_id="Qwen/Qwen3-32B",
            required_secret_keys=("api_key",),
            required_config_keys=("model_id",),
            capability_flags=("chat", "embeddings"),
            model_hints=(
                "Qwen/Qwen3-32B",
                "Qwen/Qwen3-235B-A22B",
                "deepseek-ai/DeepSeek-V3.2",
                "moonshotai/Kimi-K2-Instruct",
            ),
            supports_custom_base_url=False,
            listing_priority=63,
            docs_url="https://docs.siliconflow.com/cn/api-reference/chat-completions/chat-completions",
            provider_kind="aggregator",
            auth_method="api_key",
            auth_type="api_key",
            env_var_names=("SILICONFLOW_API_KEY",),
            base_url_env_var="SILICONFLOW_BASE_URL",
            metadata={"surface": "aggregator", "unsupported_capabilities": "reasoning"},
        ),
        ProviderDefinition(
            provider_id="volcengine",
            display_name="Volcengine Ark / Doubao",
            transport_id="openai_chat_compatible",
            catalog_summary="Use Volcengine Ark and Doubao models through Ark's OpenAI-compatible endpoint.",
            onboarding_hint="Attach an Ark API key, choose a Doubao model or endpoint id, and validate the China-region route.",
            default_base_url="https://ark.cn-beijing.volces.com/api/v3",
            default_model_id="doubao-1-5-pro-32k-250115",
            endpoint_path_override="/chat/completions",
            required_secret_keys=("api_key",),
            required_config_keys=("model_id",),
            capability_flags=("chat",),
            model_hints=(
                "doubao-1-5-pro-32k-250115",
                "doubao-1-5-pro-256k-250115",
                "doubao-seed-1-6-250615",
                "doubao-seed-1-6-thinking-250615",
            ),
            supports_custom_base_url=False,
            listing_priority=64,
            docs_url="https://www.volcengine.com/docs/82379/1330626",
            provider_kind="first_party",
            auth_method="api_key",
            auth_type="api_key",
            env_var_names=("ARK_API_KEY", "VOLCENGINE_API_KEY"),
            base_url_env_var="VOLCENGINE_BASE_URL",
            metadata={"surface": "first_party", "unsupported_capabilities": "reasoning,embeddings"},
        ),
        ProviderDefinition(
            provider_id="baidu-qianfan",
            display_name="Baidu Qianfan / Wenxin",
            transport_id="openai_chat_compatible",
            catalog_summary="Use Baidu Qianfan ModelBuilder and Wenxin-compatible models through the v2 OpenAI-compatible API.",
            onboarding_hint="Attach a Qianfan API key, select an ERNIE or DeepSeek model, and validate the v2 chat route.",
            default_base_url="https://qianfan.baidubce.com/v2",
            default_model_id="ernie-4.0-turbo-8k",
            endpoint_path_override="/chat/completions",
            required_secret_keys=("api_key",),
            required_config_keys=("model_id",),
            capability_flags=("chat",),
            model_hints=("ernie-4.0-turbo-8k", "ernie-3.5-8k", "deepseek-v3.2", "deepseek-r1"),
            supports_custom_base_url=False,
            listing_priority=67,
            docs_url="https://cloud.baidu.com/doc/qianfan-docs/s/Fm9l6ocai",
            provider_kind="first_party",
            auth_method="api_key",
            auth_type="api_key",
            env_var_names=("QIANFAN_API_KEY", "BAIDU_QIANFAN_API_KEY"),
            base_url_env_var="QIANFAN_BASE_URL",
            metadata={"surface": "first_party", "unsupported_capabilities": "reasoning,embeddings"},
        ),
        ProviderDefinition(
            provider_id="tencent-hunyuan",
            display_name="Tencent Hunyuan",
            transport_id="openai_chat_compatible",
            catalog_summary="Use Tencent Hunyuan through Tencent Cloud's OpenAI-compatible API.",
            onboarding_hint="Attach a Hunyuan API key and choose a Tencent-hosted model such as Hunyuan Turbos.",
            default_base_url="https://api.hunyuan.cloud.tencent.com/v1",
            default_model_id="hunyuan-turbos-latest",
            required_secret_keys=("api_key",),
            required_config_keys=("model_id",),
            capability_flags=("chat", "embeddings"),
            model_hints=("hunyuan-turbos-latest", "hunyuan-t1-latest", "hunyuan-a13b-instruct"),
            supports_custom_base_url=False,
            listing_priority=68,
            docs_url="https://cloud.tencent.com/document/product/1729/111007",
            provider_kind="first_party",
            auth_method="api_key",
            auth_type="api_key",
            env_var_names=("HUNYUAN_API_KEY", "TENCENT_HUNYUAN_API_KEY"),
            base_url_env_var="HUNYUAN_BASE_URL",
            metadata={"surface": "first_party", "unsupported_capabilities": "reasoning"},
        ),
        ProviderDefinition(
            provider_id="tencent-tokenhub",
            display_name="Tencent Cloud TokenHub",
            transport_id="openai_chat_compatible",
            catalog_summary="Use Tencent Cloud TokenHub as an OpenAI-compatible gateway for Hunyuan and third-party models.",
            onboarding_hint="Attach a TokenHub API key and choose a TokenHub service ID such as hy3-preview or deepseek-v3.2.",
            default_base_url="https://tokenhub.tencentmaas.com/v1",
            default_model_id="hy3-preview",
            required_secret_keys=("api_key",),
            required_config_keys=("model_id",),
            capability_flags=("chat",),
            model_hints=(
                "hy3-preview",
                "deepseek-v3.2",
                "deepseek-r1",
                "glm-5",
                "kimi-k2.5",
                "minimax-m2.5",
            ),
            supports_custom_base_url=False,
            listing_priority=68,
            docs_url="https://cloud.tencent.com/document/product/1823/130079",
            provider_kind="aggregator",
            auth_method="api_key",
            auth_type="api_key",
            env_var_names=("TOKENHUB_API_KEY", "TENCENT_TOKENHUB_API_KEY"),
            base_url_env_var="TOKENHUB_BASE_URL",
            metadata={"surface": "aggregator", "unsupported_capabilities": "reasoning,embeddings"},
        ),
        ProviderDefinition(
            provider_id="stepfun",
            display_name="StepFun",
            transport_id="openai_chat_compatible",
            catalog_summary="Use StepFun's Step models through the OpenAI-compatible chat endpoint.",
            onboarding_hint="Attach a StepFun API key, select a Step model, and validate the compatible chat route.",
            default_base_url="https://api.stepfun.com/v1",
            default_model_id="step-3.5-flash",
            required_secret_keys=("api_key",),
            required_config_keys=("model_id",),
            capability_flags=("chat",),
            model_hints=("step-3.5-flash", "step-3.5", "step-2-16k", "step-1v-8k"),
            supports_custom_base_url=False,
            listing_priority=69,
            docs_url="https://platform.stepfun.com/docs/guide/openai",
            provider_kind="first_party",
            auth_method="api_key",
            auth_type="api_key",
            env_var_names=("STEPFUN_API_KEY", "STEP_API_KEY"),
            base_url_env_var="STEPFUN_BASE_URL",
            metadata={"surface": "first_party", "unsupported_capabilities": "reasoning,embeddings"},
        ),
        ProviderDefinition(
            provider_id="modelscope",
            display_name="ModelScope",
            transport_id="openai_chat_compatible",
            catalog_summary="Use ModelScope API Inference as an OpenAI-compatible route to popular open-source models.",
            onboarding_hint="Attach a ModelScope access token and choose a hosted Qwen, GLM, DeepSeek, or Kimi model.",
            default_base_url="https://api-inference.modelscope.cn/v1",
            default_model_id="Qwen/Qwen3-235B-A22B-Instruct-2507",
            required_secret_keys=("api_key",),
            required_config_keys=("model_id",),
            capability_flags=("chat", "embeddings"),
            model_hints=(
                "Qwen/Qwen3-235B-A22B-Instruct-2507",
                "Qwen/Qwen3-Coder-30B-A3B-Instruct",
                "ZhipuAI/GLM-4.6",
            ),
            supports_custom_base_url=False,
            listing_priority=77,
            docs_url="https://www.modelscope.cn/docs/model-service/API-Inference/intro",
            provider_kind="aggregator",
            auth_method="api_key",
            auth_type="api_key",
            env_var_names=("MODELSCOPE_API_KEY",),
            base_url_env_var="MODELSCOPE_BASE_URL",
            metadata={"surface": "aggregator", "unsupported_capabilities": "reasoning"},
        ),
    )
