"""Owner-aligned operator projections for CLI and API inspection surfaces."""

from .runtime import (
    DashboardAlert,
    DashboardCapabilityRecord,
    DashboardEggRecord,
    DashboardControlRecord,
    DashboardDetailItem,
    DashboardStateLaneRecord,
    DashboardHeartbeat,
    DashboardMeta,
    DashboardMetric,
    DashboardOpsRecord,
    DashboardOverviewSurface,
    DashboardProgressionRecord,
    DashboardProviderReadiness,
    DashboardProviderProfileRecord,
    DashboardSessionRecord,
    DashboardSurface,
    DashboardTimelineEvent,
    ProcedureOperatorDetail,
    ProcedureOperatorSurface,
    ProfileOperatorSurface,
    build_canonical_procedure_detail,
    build_dashboard_surface,
    build_procedure_operator_surface,
    build_profile_operator_surface,
    dashboard_surface_record,
    render_procedure_lines,
    render_profile_lines,
)
from .typer_support import run_typer_app
from .cli_cards import CliCardSection

__all__ = [
    "DashboardAlert",
    "DashboardCapabilityRecord",
    "DashboardEggRecord",
    "DashboardControlRecord",
    "DashboardDetailItem",
    "DashboardStateLaneRecord",
    "DashboardHeartbeat",
    "DashboardMeta",
    "DashboardMetric",
    "DashboardOpsRecord",
    "DashboardOverviewSurface",
    "DashboardProgressionRecord",
    "DashboardProviderReadiness",
    "DashboardProviderProfileRecord",
    "DashboardSessionRecord",
    "DashboardSurface",
    "DashboardTimelineEvent",
    "ProcedureOperatorDetail",
    "ProcedureOperatorSurface",
    "ProfileOperatorSurface",
    "build_canonical_procedure_detail",
    "build_dashboard_surface",
    "build_procedure_operator_surface",
    "build_profile_operator_surface",
    "CliCardSection",
    "dashboard_surface_record",
    "render_procedure_lines",
    "render_profile_lines",
    "run_typer_app",
]
