from __future__ import annotations

import ast
import json
from pathlib import Path
from typing import Iterable

try:
    import yaml
except ImportError:
    yaml = None  # type: ignore[assignment]


ROOT = Path(__file__).resolve().parents[3]
HARNESS_ROOT = ROOT / "tools" / "agent"
PUBLIC_CONTRACTS_PATH = HARNESS_ROOT / "public-contracts.yaml"
PUBLIC_CONTRACTS_DOC_PATH = ROOT / "docs" / "agent" / "public-contracts.md"


def load_manifest(path: Path) -> dict[str, object]:
    text = path.read_text(encoding="utf-8")
    if yaml is not None:
        try:
            return yaml.safe_load(text) or {}
        except Exception:
            pass
    try:
        return json.loads(text)
    except json.JSONDecodeError as exc:
        raise SystemExit(f"failed to parse {path}: {exc}") from exc


PUBLIC_CONTRACT_REQUIRED_SECTIONS = (
    "http_routes",
    "cli_commands",
    "shell_commands",
    "gateway_commands",
    "package_exports",
    "compatibility_contracts",
    "storage_schema",
    "release_contracts",
    "surface_contracts",
    "runtime_resource_contracts",
    "tool_schemas",
)
PUBLIC_CONTRACT_SECTION_TITLES = {
    "http_routes": "HTTP Routes",
    "cli_commands": "CLI Commands",
    "shell_commands": "Shell Commands",
    "gateway_commands": "Gateway Commands",
    "package_exports": "Package Exports",
    "compatibility_contracts": "Compatibility Contracts",
    "storage_schema": "Storage Schema",
    "release_contracts": "Release Contracts",
    "surface_contracts": "Surface Contracts",
    "runtime_resource_contracts": "Runtime Resource Contracts",
    "tool_schemas": "Tool Schemas",
}
PUBLIC_CONTRACT_DOC_HEADER = "\n".join(
    (
        "# Public Contract Inventory",
        "",
        "<!-- Generated by `make agent-public-contracts-docs`; do not edit by hand. -->",
        "",
        "This document is generated from "
        "[tools/agent/public-contracts.yaml](../../tools/agent/public-contracts.yaml). "
        "It gives maintainers and coding agents a stable index of externally visible "
        "routes, commands, package exports, compatibility surfaces, release surfaces, "
        "runtime resource owners, and tool schemas.",
        "",
    )
)


def public_contract_inventory_errors(
    *,
    root: Path = ROOT,
    path: Path = PUBLIC_CONTRACTS_PATH,
    required_sections: Iterable[str] = PUBLIC_CONTRACT_REQUIRED_SECTIONS,
) -> list[str]:
    if not path.exists():
        return [f"missing public contract inventory: {path.relative_to(root)}"]
    inventory = load_manifest(path)
    if not isinstance(inventory, dict):
        return [f"public contract inventory must be a mapping: {path.relative_to(root)}"]

    errors: list[str] = []
    for section in required_sections:
        entries = inventory.get(section)
        if not isinstance(entries, list) or not entries:
            errors.append(f"public contract section must be a non-empty list: {section}")
            continue
        for index, entry in enumerate(entries):
            if section == "package_exports":
                errors.extend(_public_package_export_errors(entry, section=section, index=index, root=root))
            else:
                errors.extend(_public_contract_entry_errors(entry, section=section, index=index, root=root))
    return errors


def public_contract_docs_errors(
    *,
    root: Path = ROOT,
    inventory_path: Path = PUBLIC_CONTRACTS_PATH,
    doc_path: Path = PUBLIC_CONTRACTS_DOC_PATH,
    required_sections: Iterable[str] = PUBLIC_CONTRACT_REQUIRED_SECTIONS,
) -> list[str]:
    if not doc_path.exists():
        return [
            f"missing generated public contract docs: {doc_path.relative_to(root)} "
            "(run make agent-public-contracts-docs)"
        ]
    expected = render_public_contract_inventory_markdown(
        root=root,
        inventory_path=inventory_path,
        required_sections=required_sections,
    )
    try:
        actual = doc_path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        return [f"generated public contract docs are not UTF-8 readable: {doc_path.relative_to(root)}"]
    if actual != expected:
        return [
            f"generated public contract docs are stale: {doc_path.relative_to(root)} "
            "(run make agent-public-contracts-docs)"
        ]
    return []


def render_public_contract_inventory_markdown(
    *,
    root: Path = ROOT,
    inventory_path: Path = PUBLIC_CONTRACTS_PATH,
    required_sections: Iterable[str] = PUBLIC_CONTRACT_REQUIRED_SECTIONS,
) -> str:
    inventory = load_manifest(inventory_path)
    if not isinstance(inventory, dict):
        raise SystemExit(f"public contract inventory must be a mapping: {inventory_path.relative_to(root)}")

    lines = [PUBLIC_CONTRACT_DOC_HEADER.rstrip(), ""]
    for section in required_sections:
        entries = inventory.get(section, [])
        title = PUBLIC_CONTRACT_SECTION_TITLES.get(section, section.replace("_", " ").title())
        lines.append(f"## {title}")
        lines.append("")
        if not isinstance(entries, list) or not entries:
            lines.append("_No entries._")
            lines.append("")
            continue
        lines.append("| ID | Contract | Owner | Path | Doc | Markers |")
        lines.append("| --- | --- | --- | --- | --- | --- |")
        for entry in entries:
            if not isinstance(entry, dict):
                continue
            lines.append(_public_contract_markdown_row(entry, section))
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def write_public_contract_inventory_docs(
    *,
    root: Path = ROOT,
    inventory_path: Path = PUBLIC_CONTRACTS_PATH,
    doc_path: Path = PUBLIC_CONTRACTS_DOC_PATH,
    required_sections: Iterable[str] = PUBLIC_CONTRACT_REQUIRED_SECTIONS,
) -> None:
    markdown = render_public_contract_inventory_markdown(
        root=root,
        inventory_path=inventory_path,
        required_sections=required_sections,
    )
    doc_path.parent.mkdir(parents=True, exist_ok=True)
    doc_path.write_text(markdown, encoding="utf-8")
    print(f"wrote {doc_path.relative_to(root)}")


def _public_contract_markdown_row(entry: dict[object, object], section: str) -> str:
    label = _public_contract_entry_label(entry, section, 0)
    contract = _public_contract_contract_label(entry, section)
    owner = _markdown_cell_code_path(entry.get("owner"))
    path = _markdown_cell_code_path(entry.get("path"))
    doc = _markdown_cell_code_path(entry.get("doc"))
    markers = _public_contract_marker_summary(entry)
    return (
        f"| {_markdown_escape(label)} "
        f"| {_markdown_escape(contract)} "
        f"| {owner} "
        f"| {path} "
        f"| {doc} "
        f"| {markers} |"
    )


def _public_contract_contract_label(entry: dict[object, object], section: str) -> str:
    if section == "package_exports":
        package = str(entry.get("package") or "")
        exports = entry.get("exports")
        if isinstance(exports, list):
            export_text = ", ".join(str(export) for export in exports if isinstance(export, str))
            return f"{package}: {export_text}" if export_text else package
        return package
    for key in ("method", "command", "path", "id"):
        value = entry.get(key)
        if not isinstance(value, str) or not value.strip():
            continue
        if key == "method":
            route = entry.get("path")
            if isinstance(route, str) and route.strip():
                return f"{value} {route}"
        return value
    return ""


def _public_contract_marker_summary(entry: dict[object, object]) -> str:
    contains = entry.get("contains")
    if not isinstance(contains, list) or not contains:
        return "-"
    marker_text = ", ".join(f"`{_markdown_escape(str(marker))}`" for marker in contains if isinstance(marker, str))
    return marker_text or "-"


def _markdown_cell_code_path(value: object) -> str:
    if not isinstance(value, str) or not value.strip():
        return "-"
    return f"`{_markdown_escape(value)}`"


def _markdown_escape(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ")


def _public_contract_entry_label(entry: object, section: str, index: int) -> str:
    if isinstance(entry, dict):
        for key in ("id", "package", "command", "path"):
            value = entry.get(key)
            if isinstance(value, str) and value.strip():
                return value.strip()
    return f"{section}[{index}]"


def _public_contract_entry_errors(
    entry: object,
    *,
    section: str,
    index: int,
    root: Path,
) -> list[str]:
    label = _public_contract_entry_label(entry, section, index)
    if not isinstance(entry, dict):
        return [f"public contract entry must be a mapping: {label}"]

    errors: list[str] = []
    if not isinstance(entry.get("id"), str) or not str(entry.get("id")).strip():
        errors.append(f"public contract entry is missing id: {label}")

    anchor_keys = [key for key in ("owner", "doc") if key in entry]
    if (
        section
        in {
            "compatibility_contracts",
            "storage_schema",
            "release_contracts",
            "surface_contracts",
            "runtime_resource_contracts",
        }
        and "path" in entry
    ):
        anchor_keys.append("path")
    if not anchor_keys:
        errors.append(f"public contract entry needs owner, path, or doc anchor: {label}")

    for key in anchor_keys:
        raw_value = entry.get(key)
        if not isinstance(raw_value, str) or not raw_value.strip():
            errors.append(f"public contract {label} has empty {key}")
            continue
        target = root / raw_value
        if target.exists():
            continue
        errors.append(f"public contract {label} references missing {key}: {raw_value}")

    contains = entry.get("contains", [])
    if contains is None:
        contains = []
    if not isinstance(contains, list):
        errors.append(f"public contract {label} contains must be a list")
        return errors
    owner = entry.get("owner") or entry.get("path")
    if not contains or not isinstance(owner, str) or not owner.strip():
        return errors

    owner_path = root / owner
    if not owner_path.exists() or not owner_path.is_file():
        return errors
    try:
        owner_text = owner_path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        errors.append(f"public contract {label} owner is not UTF-8 readable: {owner}")
        return errors
    for marker in contains:
        if not isinstance(marker, str) or not marker.strip():
            errors.append(f"public contract {label} contains marker must be non-empty text")
            continue
        if marker not in owner_text:
            errors.append(f"public contract {label} missing owner marker in {owner}: {marker}")
    return errors


def _public_package_export_errors(
    entry: object,
    *,
    section: str,
    index: int,
    root: Path,
) -> list[str]:
    label = _public_contract_entry_label(entry, section, index)
    if not isinstance(entry, dict):
        return [f"public contract entry must be a mapping: {label}"]

    errors = _public_contract_entry_errors(
        {"id": entry.get("package"), "owner": entry.get("owner")},
        section=section,
        index=index,
        root=root,
    )
    exports = entry.get("exports")
    if not isinstance(exports, list) or not exports:
        errors.append(f"public package export entry needs non-empty exports: {label}")
        return errors
    expected_exports = tuple(str(export) for export in exports if isinstance(export, str) and export.strip())
    if len(expected_exports) != len(exports):
        errors.append(f"public package export entry has invalid export name: {label}")

    owner = entry.get("owner")
    if not isinstance(owner, str) or not owner.strip():
        return errors
    owner_path = root / owner
    if not owner_path.exists():
        return errors
    exported_names = _python_dunder_all_names(owner_path)
    if not exported_names:
        errors.append(f"public package export entry has no static __all__: {label}")
        return errors
    for export in expected_exports:
        if export not in exported_names:
            errors.append(f"public package export missing from {owner}: {export}")
    return errors


def _python_dunder_all_names(path: Path) -> tuple[str, ...]:
    try:
        tree = ast.parse(path.read_text(encoding="utf-8"))
    except (SyntaxError, UnicodeDecodeError):
        return ()
    for node in tree.body:
        value: ast.expr | None = None
        if isinstance(node, ast.Assign):
            if any(isinstance(target, ast.Name) and target.id == "__all__" for target in node.targets):
                value = node.value
        elif isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name) and node.target.id == "__all__":
            value = node.value
        if value is not None:
            return _literal_string_sequence(value)
    return ()


def _literal_string_sequence(node: ast.expr) -> tuple[str, ...]:
    if not isinstance(node, (ast.List, ast.Tuple, ast.Set)):
        return ()
    values: list[str] = []
    for item in node.elts:
        if isinstance(item, ast.Constant) and isinstance(item.value, str):
            values.append(item.value)
    return tuple(values)
